HalfCheetah-v5:
  trial_number: 37
  value: 769.4943016
  params:
    n_steps: 16
    gamma: 0.95
    learning_rate: 0.0006115378553216117
    n_critic_updates: 25
    cg_max_steps: 10
    target_kl: 0.02
    gae_lambda: 1
    batch_size: 1024
    net_arch: large
    activation_fn: tanh
    entropy_coef: 0.49
    sampling_coef: 0.14000000000000012
    epsilon: 0.7000000000000001
    orthogonal_init: 1
    n_timesteps: 100000
    n_envs: 8
    normalize_advantage: 1
  comment: 'Best trial details: _number=37, state=1, _values=[769.4943016], _datetime_start=2025-03-16
    20:56:29.669133, datetime_complete=2025-03-17 05:55:14.837352, _params={''n_steps'':
    16, ''gamma'': 0.95, ''learning_rate'': 0.0006115378553216117, ''n_critic_updates'':
    25, ''cg_max_steps'': 10, ''target_kl'': 0.02, ''gae_lambda'': 1.0, ''batch_size'':
    1024, ''net_arch'': ''large'', ''activation_fn'': ''tanh'', ''entropy_coef'':
    0.49, ''sampling_coef'': 0.14000000000000012, ''epsilon'': 0.7000000000000001,
    ''orthogonal_init'': True, ''n_timesteps'': 100000, ''n_envs'': 8, ''normalize_advantage'':
    True}, _user_attrs={}, _system_attrs={''completed_rung_0'': 209.48079719999996},
    intermediate_values={1: 209.48079719999996, 2: 769.4943016}, _distributions={''n_steps'':
    CategoricalDistribution(choices=(8, 16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'':
    CategoricalDistribution(choices=(0.8, 0.85, 0.9, 0.95, 0.99)), ''learning_rate'':
    FloatDistribution(high=1.0, log=True, low=1e-05, step=None), ''n_critic_updates'':
    CategoricalDistribution(choices=(5, 10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03,
    0.02, 0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8,
    0.9, 0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256,
    512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False))}, _trial_id=37'
Hopper-v5:
  trial_number: 63
  value: 1735.2231371999999
  params:
    n_steps: 128
    gamma: 0.99
    learning_rate: 0.0008758107610955626
    n_critic_updates: 30
    cg_max_steps: 25
    target_kl: 0.01
    gae_lambda: 0.92
    batch_size: 2048
    net_arch: small
    activation_fn: relu
    entropy_coef: -0.22999999999999998
    sampling_coef: -0.47
    epsilon: 0.45000000000000007
    orthogonal_init: 1
    n_timesteps: 100000
    n_envs: 4
    normalize_advantage: 1
  comment: 'Best trial details: _number=63, state=1, _values=[1735.2231371999999],
    _datetime_start=2025-03-18 23:59:18.920601, datetime_complete=2025-03-19 01:37:29.618333,
    _params={''n_steps'': 128, ''gamma'': 0.99, ''learning_rate'': 0.0008758107610955626,
    ''n_critic_updates'': 30, ''cg_max_steps'': 25, ''target_kl'': 0.01, ''gae_lambda'':
    0.92, ''batch_size'': 2048, ''net_arch'': ''small'', ''activation_fn'': ''relu'',
    ''entropy_coef'': -0.22999999999999998, ''sampling_coef'': -0.47, ''epsilon'':
    0.45000000000000007, ''orthogonal_init'': True, ''n_timesteps'': 100000, ''n_envs'':
    4, ''normalize_advantage'': True}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    592.0901719999999}, intermediate_values={1: 592.0901719999999, 2: 1735.2231371999999},
    _distributions={''n_steps'': CategoricalDistribution(choices=(8, 16, 32, 64, 128,
    256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8, 0.85,
    0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True, low=1e-05,
    step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20, 25, 30)),
    ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02, 0.01, 0.005,
    0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9, 0.92, 0.95,
    0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256, 512,
    1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False))}, _trial_id=63'
Humanoid-v5:
  trial_number: 457
  value: 549.3199836
  params:
    n_steps: 512
    gamma: 0.95
    learning_rate: 0.03648542602737527
    n_critic_updates: 20
    cg_max_steps: 5
    target_kl: 0.03
    gae_lambda: 0.95
    batch_size: 2048
    net_arch: medium
    activation_fn: tanh
    entropy_coef: -0.59
    sampling_coef: -0.69
    buffer_capacity: 30000
    epsilon: 0.15000000000000002
    orthogonal_init: 0
    n_timesteps: 600000
    n_envs: 6
    normalize_advantage: 1
  comment: 'Best trial details: _number=457, state=1, _values=[549.3199836], _datetime_start=2025-02-10
    19:17:51.271311, datetime_complete=2025-02-11 13:47:09.006567, _params={''n_steps'':
    512, ''gamma'': 0.95, ''learning_rate'': 0.03648542602737527, ''n_critic_updates'':
    20, ''cg_max_steps'': 5, ''target_kl'': 0.03, ''gae_lambda'': 0.95, ''batch_size'':
    2048, ''net_arch'': ''medium'', ''activation_fn'': ''tanh'', ''entropy_coef'':
    -0.59, ''sampling_coef'': -0.69, ''buffer_capacity'': 30000, ''epsilon'': 0.15000000000000002,
    ''orthogonal_init'': False, ''n_timesteps'': 600000, ''n_envs'': 6, ''normalize_advantage'':
    True}, _user_attrs={}, _system_attrs={''completed_rung_0'': 316.22615940000003,
    ''completed_rung_1'': 426.53696419999994}, intermediate_values={1: 316.22615940000003,
    2: 378.65377419999993, 3: 326.2807844, 4: 426.53696419999994, 5: 457.94943939999996,
    6: 532.5921612, 7: 323.3078792, 8: 389.864273, 9: 451.02922639999997, 10: 505.0701563999999,
    11: 361.63867919999996, 12: 459.48226480000005, 13: 443.88220220000005, 14: 549.3199836},
    _distributions={''n_steps'': CategoricalDistribution(choices=(8, 16, 32, 64, 128,
    256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8, 0.85,
    0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True, low=1e-05,
    step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20, 25, 30)),
    ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02, 0.01, 0.005,
    0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9, 0.92, 0.95,
    0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256, 512,
    1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10)), ''normalize_advantage'': CategoricalDistribution(choices=(True,
    False))}, _trial_id=457'
HumanoidStandup-v5:
  trial_number: 58
  value: 120974.9668076
  params:
    n_steps: 8
    gamma: 0.8
    learning_rate: 0.11959944479404305
    n_critic_updates: 30
    cg_max_steps: 5
    target_kl: 0.1
    gae_lambda: 1
    batch_size: 2048
    net_arch: large
    activation_fn: tanh
    entropy_coef: 0.24
    sampling_coef: -0.5
    epsilon: 0.75
    orthogonal_init: 1
    n_timesteps: 100000
    n_envs: 4
    normalize_advantage: 0
  comment: 'Best trial details: _number=58, state=1, _values=[120974.9668076], _datetime_start=2025-03-21
    01:33:45.140111, datetime_complete=2025-03-21 16:23:39.362318, _params={''n_steps'':
    8, ''gamma'': 0.8, ''learning_rate'': 0.11959944479404305, ''n_critic_updates'':
    30, ''cg_max_steps'': 5, ''target_kl'': 0.1, ''gae_lambda'': 1.0, ''batch_size'':
    2048, ''net_arch'': ''large'', ''activation_fn'': ''tanh'', ''entropy_coef'':
    0.24, ''sampling_coef'': -0.5, ''epsilon'': 0.75, ''orthogonal_init'': True, ''n_timesteps'':
    100000, ''n_envs'': 4, ''normalize_advantage'': False}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    85499.89313499999}, intermediate_values={1: 85499.89313499999, 2: 120974.9668076},
    _distributions={''n_steps'': CategoricalDistribution(choices=(8, 16, 32, 64, 128,
    256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8, 0.85,
    0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True, low=1e-05,
    step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20, 25, 30)),
    ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02, 0.01, 0.005,
    0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9, 0.92, 0.95,
    0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256, 512,
    1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False))}, _trial_id=58'
InvertedPendulum-v5:
  trial_number: 24
  value: 1000
  params:
    n_steps: 1024
    gamma: 0.99
    learning_rate: 0.0004370180574646787
    n_critic_updates: 30
    cg_max_steps: 30
    target_kl: 0.03
    gae_lambda: 0.95
    batch_size: 256
    net_arch: large
    activation_fn: tanh
    entropy_coef: -0.81
    sampling_coef: -0.27
    epsilon: 0.15000000000000002
    orthogonal_init: 0
    n_timesteps: 100000
    n_envs: 8
    normalize_advantage: 1
  comment: 'Best trial details: _number=24, state=1, _values=[1000.0], _datetime_start=2025-03-22
    15:07:12.971088, datetime_complete=2025-03-22 15:17:30.994619, _params={''n_steps'':
    1024, ''gamma'': 0.99, ''learning_rate'': 0.0004370180574646787, ''n_critic_updates'':
    30, ''cg_max_steps'': 30, ''target_kl'': 0.03, ''gae_lambda'': 0.95, ''batch_size'':
    256, ''net_arch'': ''large'', ''activation_fn'': ''tanh'', ''entropy_coef'': -0.81,
    ''sampling_coef'': -0.27, ''epsilon'': 0.15000000000000002, ''orthogonal_init'':
    False, ''n_timesteps'': 100000, ''n_envs'': 8, ''normalize_advantage'': True},
    _user_attrs={}, _system_attrs={''completed_rung_0'': 130.4}, intermediate_values={1:
    130.4, 2: 1000.0}, _distributions={''n_steps'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8,
    0.85, 0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True,
    low=1e-05, step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02,
    0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9,
    0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256,
    512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False))}, _trial_id=24'
