HalfCheetah-v5:
  trial_number: 144
  value: 1022.3893396
  params:
    n_steps: 512
    gamma: 0.99
    learning_rate: 0.019585504996402117
    n_critic_updates: 30
    cg_max_steps: 5
    target_kl: 0.005
    gae_lambda: 0.92
    batch_size: 1024
    net_arch: small
    activation_fn: tanh
    entropy_coef: -0.26
    sampling_coef: -0.42999999999999994
    buffer_capacity: 38000
    epsilon: 0.35
    orthogonal_init: 1
    n_timesteps: 100000
    n_envs: 2
    normalize_advantage: 0
    buffer_alpha: 0.2554118489002918
  comment: 'Best trial details: _number=144, state=1, _values=[1022.3893396], _datetime_start=2025-03-16
    23:50:48.325568, datetime_complete=2025-03-17 00:14:22.999019, _params={''n_steps'':
    512, ''gamma'': 0.99, ''learning_rate'': 0.019585504996402117, ''n_critic_updates'':
    30, ''cg_max_steps'': 5, ''target_kl'': 0.005, ''gae_lambda'': 0.92, ''batch_size'':
    1024, ''net_arch'': ''small'', ''activation_fn'': ''tanh'', ''entropy_coef'':
    -0.26, ''sampling_coef'': -0.42999999999999994, ''buffer_capacity'': 38000, ''epsilon'':
    0.35, ''orthogonal_init'': True, ''n_timesteps'': 100000, ''n_envs'': 2, ''normalize_advantage'':
    False, ''buffer_alpha'': 0.2554118489002918}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    76.54355100000001}, intermediate_values={1: 76.54355100000001, 2: 1022.3893396},
    _distributions={''n_steps'': CategoricalDistribution(choices=(8, 16, 32, 64, 128,
    256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8, 0.85,
    0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True, low=1e-05,
    step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20, 25, 30)),
    ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02, 0.01, 0.005,
    0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9, 0.92, 0.95,
    0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256, 512,
    1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False)), ''buffer_alpha'': FloatDistribution(high=1.0,
    log=True, low=0.1, step=None)}, _trial_id=144'
Hopper-v5:
  trial_number: 110
  value: 1137.5700554
  params:
    n_steps: 512
    gamma: 0.99
    learning_rate: 0.17649784710013225
    n_critic_updates: 20
    cg_max_steps: 5
    target_kl: 0.03
    gae_lambda: 1
    batch_size: 2048
    net_arch: medium
    activation_fn: relu
    entropy_coef: -0.45999999999999996
    sampling_coef: -0.8200000000000001
    buffer_capacity: 53000
    epsilon: 0.2
    orthogonal_init: 1
    n_timesteps: 100000
    n_envs: 8
    normalize_advantage: 0
    buffer_alpha: 0.3037402388348216
  comment: 'Best trial details: _number=110, state=1, _values=[1137.5700554], _datetime_start=2025-03-18
    18:41:54.442534, datetime_complete=2025-03-18 18:48:55.872325, _params={''n_steps'':
    512, ''gamma'': 0.99, ''learning_rate'': 0.17649784710013225, ''n_critic_updates'':
    20, ''cg_max_steps'': 5, ''target_kl'': 0.03, ''gae_lambda'': 1.0, ''batch_size'':
    2048, ''net_arch'': ''medium'', ''activation_fn'': ''relu'', ''entropy_coef'':
    -0.45999999999999996, ''sampling_coef'': -0.8200000000000001, ''buffer_capacity'':
    53000, ''epsilon'': 0.2, ''orthogonal_init'': True, ''n_timesteps'': 100000, ''n_envs'':
    8, ''normalize_advantage'': False, ''buffer_alpha'': 0.3037402388348216}, _user_attrs={},
    _system_attrs={''completed_rung_0'': 325.0579108}, intermediate_values={1: 325.0579108,
    2: 1137.5700554}, _distributions={''n_steps'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8,
    0.85, 0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True,
    low=1e-05, step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02,
    0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9,
    0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256,
    512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False)), ''buffer_alpha'': FloatDistribution(high=1.0,
    log=True, low=0.1, step=None)}, _trial_id=110'
Humanoid-v5:
  trial_number: 78
  value: 425.2933906
  params:
    n_steps: 64
    gamma: 0.99
    learning_rate: 0.001765494595109263
    n_critic_updates: 10
    cg_max_steps: 20
    target_kl: 0.05
    gae_lambda: 0.9
    batch_size: 256
    net_arch: large
    activation_fn: tanh
    entropy_coef: 0.14000000000000012
    sampling_coef: -0.9299999999999999
    buffer_capacity: 84000
    epsilon: 0.7000000000000001
    orthogonal_init: 1
    n_timesteps: 400000
    n_envs: 2
    normalize_advantage: 1
    buffer_alpha: 0.343423270490337
  comment: 'Best trial details: _number=78, state=1, _values=[425.2933906], _datetime_start=2025-02-07
    11:35:28.840846, datetime_complete=2025-02-07 12:13:17.875458, _params={''n_steps'':
    64, ''gamma'': 0.99, ''learning_rate'': 0.001765494595109263, ''n_critic_updates'':
    10, ''cg_max_steps'': 20, ''target_kl'': 0.05, ''gae_lambda'': 0.9, ''batch_size'':
    256, ''net_arch'': ''large'', ''activation_fn'': ''tanh'', ''entropy_coef'': 0.14000000000000012,
    ''sampling_coef'': -0.9299999999999999, ''buffer_capacity'': 84000, ''epsilon'':
    0.7000000000000001, ''orthogonal_init'': True, ''n_timesteps'': 400000, ''n_envs'':
    2, ''normalize_advantage'': True, ''buffer_alpha'': 0.343423270490337}, _user_attrs={},
    _system_attrs={''completed_rung_0'': 315.7868884, ''completed_rung_1'': 382.53918239999996,
    ''completed_rung_2'': 429.4404152}, intermediate_values={1: 315.7868884, 2: 305.83557899999994,
    3: 291.3353462, 4: 382.53918239999996, 5: 303.4738554, 6: 306.4449222, 7: 250.0747528,
    8: 402.792335, 9: 305.0334414, 10: 257.0309064, 11: 250.7797352, 12: 374.22383460000003,
    13: 473.4332066, 14: 316.3016928, 15: 251.3656664, 16: 429.4404152, 17: 444.9788546,
    18: 425.2933906}, _distributions={''n_steps'': CategoricalDistribution(choices=(8,
    16, 32, 64, 128, 256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8,
    0.85, 0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True,
    low=1e-05, step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5,
    10, 20, 25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02,
    0.01, 0.005, 0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9,
    0.92, 0.95, 0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256,
    512, 1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': IntDistribution(high=1000000,
    log=False, low=100000, step=100000), ''n_envs'': CategoricalDistribution(choices=(2,
    4, 6, 8, 10)), ''normalize_advantage'': CategoricalDistribution(choices=(True,
    False)), ''buffer_alpha'': FloatDistribution(high=1.0, log=True, low=0.1, step=None)},
    _trial_id=78'
HumanoidStandup-v5:
  trial_number: 42
  value: 104717.5931542
  params:
    n_steps: 8
    gamma: 0.99
    learning_rate: 0.061739592177783645
    n_critic_updates: 20
    cg_max_steps: 5
    target_kl: 0.01
    gae_lambda: 0.98
    batch_size: 256
    net_arch: small
    activation_fn: tanh
    entropy_coef: 0.7
    sampling_coef: -0.59
    buffer_capacity: 81000
    epsilon: 0.55
    orthogonal_init: 0
    n_timesteps: 100000
    n_envs: 4
    normalize_advantage: 0
    buffer_alpha: 0.47291560915531766
  comment: 'Best trial details: _number=42, state=1, _values=[104717.5931542], _datetime_start=2025-03-20
    21:27:38.603917, datetime_complete=2025-03-20 22:05:22.430083, _params={''n_steps'':
    8, ''gamma'': 0.99, ''learning_rate'': 0.061739592177783645, ''n_critic_updates'':
    20, ''cg_max_steps'': 5, ''target_kl'': 0.01, ''gae_lambda'': 0.98, ''batch_size'':
    256, ''net_arch'': ''small'', ''activation_fn'': ''tanh'', ''entropy_coef'': 0.7,
    ''sampling_coef'': -0.59, ''buffer_capacity'': 81000, ''epsilon'': 0.55, ''orthogonal_init'':
    False, ''n_timesteps'': 100000, ''n_envs'': 4, ''normalize_advantage'': False,
    ''buffer_alpha'': 0.47291560915531766}, _user_attrs={}, _system_attrs={''completed_rung_0'':
    116366.81313280002}, intermediate_values={1: 116366.81313280002, 2: 104717.5931542},
    _distributions={''n_steps'': CategoricalDistribution(choices=(8, 16, 32, 64, 128,
    256, 512, 1024, 2048)), ''gamma'': CategoricalDistribution(choices=(0.8, 0.85,
    0.9, 0.95, 0.99)), ''learning_rate'': FloatDistribution(high=1.0, log=True, low=1e-05,
    step=None), ''n_critic_updates'': CategoricalDistribution(choices=(5, 10, 20,
    25, 30)), ''cg_max_steps'': CategoricalDistribution(choices=(5, 10, 20, 25, 30)),
    ''target_kl'': CategoricalDistribution(choices=(0.1, 0.05, 0.03, 0.02, 0.01, 0.005,
    0.001)), ''gae_lambda'': CategoricalDistribution(choices=(0.8, 0.9, 0.92, 0.95,
    0.98, 0.99, 1.0)), ''batch_size'': CategoricalDistribution(choices=(256, 512,
    1024, 2048)), ''net_arch'': CategoricalDistribution(choices=(''small'', ''medium'',
    ''large'')), ''activation_fn'': CategoricalDistribution(choices=(''tanh'', ''relu'')),
    ''entropy_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''sampling_coef'': FloatDistribution(high=1.0, log=False, low=-1.0, step=0.01),
    ''buffer_capacity'': IntDistribution(high=100000, log=False, low=10000, step=1000),
    ''epsilon'': FloatDistribution(high=0.9, log=False, low=0.1, step=0.05), ''orthogonal_init'':
    CategoricalDistribution(choices=(True, False)), ''n_timesteps'': CategoricalDistribution(choices=(100000,)),
    ''n_envs'': CategoricalDistribution(choices=(2, 4, 6, 8, 10)), ''normalize_advantage'':
    CategoricalDistribution(choices=(True, False)), ''buffer_alpha'': FloatDistribution(high=1.0,
    log=True, low=0.1, step=None)}, _trial_id=42'
