HalfCheetah-v5:
  clip_range: 0.2
  n_timesteps: 100000
  n_steps: 8
  gamma: 0.99
  learning_rate: 0.0006419987179615489
  n_critic_updates: 30
  cg_max_steps: 20
  target_kl: 0.005
  gae_lambda: 0.8
  batch_size: 512
  activation_fn: relu
  entropy_coef: -0.31999999999999995
  sampling_coef: -0.6
  epsilon: 0.25
  orthogonal_init: 0
  n_envs: 6
  normalize_advantage: 0
  net_arch: large

Hopper-v5:
  clip_range: 0.3
  n_timesteps: 100000
  n_steps: 32
  gamma: 0.95
  learning_rate: 0.0006696649996852974
  n_critic_updates: 30
  cg_max_steps: 5
  target_kl: 0.1
  gae_lambda: 0.99
  batch_size: 256
  activation_fn: tanh
  entropy_coef: -0.32999999999999996
  sampling_coef: -0.43999999999999995
  epsilon: 0.2
  orthogonal_init: 1
  n_envs: 6
  normalize_advantage: 0
  net_arch: large

Humanoid-v5:
  clip_range: 0.2
  n_timesteps: 100000
  n_steps: 32
  gamma: 0.95
  learning_rate: 2.1267809641089186e-05
  n_critic_updates: 20
  cg_max_steps: 20
  target_kl: 0.05
  gae_lambda: 1
  batch_size: 256
  net_arch: large
  activation_fn: tanh
  entropy_coef: 0.8300000000000001
  sampling_coef: 0.43999999999999995
  buffer_capacity: 69000
  epsilon: 0.4
  orthogonal_init: 1
  n_envs: 6
  normalize_advantage: 1

HumanoidStandup-v5:
  clip_range: 0.2
  n_timesteps: 100000
  n_steps: 256
  gamma: 0.99
  learning_rate: 3.421329901729236e-05
  n_critic_updates: 10
  cg_max_steps: 20
  target_kl: 0.01
  gae_lambda: 0.8
  batch_size: 512
  activation_fn: relu
  entropy_coef: -0.5800000000000001
  sampling_coef: 0.72
  epsilon: 0.25
  orthogonal_init: 1
  n_envs: 6
  normalize_advantage: 0
  net_arch: small

InvertedPendulum-v5:
  clip_range: 0.3
  n_timesteps: 100000
  n_steps: 256
  gamma: 0.85
  learning_rate: 4.487645285302108e-05
  n_critic_updates: 20
  cg_max_steps: 5
  target_kl: 0.05
  gae_lambda: 0.98
  batch_size: 256
  activation_fn: tanh
  entropy_coef: 0.24
  sampling_coef: -0.36
  epsilon: 0.45000000000000007
  orthogonal_init: 0
  n_envs: 6
  normalize_advantage: 0
  net_arch: large

Pusher-v5:
  clip_range: 0.1
  n_timesteps: 100000
  n_steps: 128
  gamma: 0.9
  learning_rate: 0.0013905015381594347
  n_critic_updates: 20
  cg_max_steps: 20
  target_kl: 0.1
  gae_lambda: 0.99
  batch_size: 2048
  activation_fn: tanh
  entropy_coef: -0.07999999999999996
  sampling_coef: -0.29000000000000004
  epsilon: 0.6
  orthogonal_init: 1
  n_envs: 8
  normalize_advantage: 0
  net_arch: medium

Reacher-v5:
  clip_range: 0.1
  n_timesteps: 100000
  n_steps: 8
  gamma: 0.8
  learning_rate: 0.00014450319773477073
  n_critic_updates: 10
  cg_max_steps: 20
  target_kl: 0.05
  gae_lambda: 0.9
  batch_size: 2048
  activation_fn: relu
  entropy_coef: -0.87
  sampling_coef: -0.21999999999999997
  epsilon: 0.8
  orthogonal_init: 1
  n_envs: 10
  normalize_advantage: 1
  net_arch: medium

