# Tuned for PPO
HalfCheetah-v5:
  normalize: true
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 64
  n_steps: 16
  gamma: 0.9
  learning_rate: 6.562333225476044e-05
  ent_coef: 2.1881234398919925e-08
  clip_range: 0.4
  n_epochs: 10
  gae_lambda: 0.99
  max_grad_norm: 5
  vf_coef: 0.47070192790845444
  net_arch: small
  activation_fn: relu
  n_envs: 10

# Tuned for PPO
Hopper-v5:
  policy: 'MlpPolicy'
  n_timesteps: 100000
  normalize: true
  batch_size: 512
  n_steps: 256
  gamma: 0.99
  learning_rate: 0.0008786509063566483
  ent_coef: 4.7413036701082044e-08
  clip_range: 0.3
  n_epochs: 5
  gae_lambda: 0.95
  max_grad_norm: 0.6
  vf_coef: 0.8162295327543241
  net_arch: small
  activation_fn: relu
  n_envs: 4

# Tuned for PPO
Humanoid-v5:
  normalize: true
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 256
  n_steps: 16
  gamma: 0.995
  learning_rate: 1.000900380783336e-05
  ent_coef: 2.034198296337839e-07
  clip_range: 0.4
  n_epochs: 20
  gae_lambda: 0.8
  max_grad_norm: 0.8
  vf_coef: 0.8304599284219261
  net_arch: tiny
  activation_fn: tanh
  n_envs: 10

# Tuned for PPO
HumanoidStandup-v5:
  normalize: true
  policy: 'MlpPolicy'
  n_timesteps: 100000
  batch_size: 512
  n_steps: 1024
  gamma: 0.9999
  learning_rate: 0.0004948905997087219
  ent_coef: 5.5364049883411455e-05
  clip_range: 0.1
  n_epochs: 10
  gae_lambda: 0.98
  max_grad_norm: 0.3
  vf_coef: 0.602511184087952
  net_arch: small
  activation_fn: tanh
  n_envs: 10
  

# Tuned for PPO
Reacher-v5:
  normalize: true
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 128
  gamma: 0.98
  learning_rate: 0.00041003062237224513
  ent_coef: 0.028522726926146675
  clip_range: 0.2
  n_epochs: 5
  gae_lambda: 0.8
  max_grad_norm: 0.8
  vf_coef: 0.7443911275358162
  net_arch: medium
  activation_fn: relu
  n_timesteps: 500000
  n_envs: 6

# Tuned for PPO
Swimmer-v5:
  normalize: true
  n_envs: 4
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 1024
  gamma: 0.9999
  learning_rate: !!float 6e-4
  gae_lambda: 0.98
  clip_range: 0.2
  n_epochs: 10
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5