Ant-v5:
  policy: 'MlpPolicy'
  batch_size: 64
  n_steps: 256
  gamma: 0.9
  learning_rate: 0.011345042877629868
  ent_coef: 0.0006300346375901035
  clip_range: 0.3
  n_epochs: 1
  gae_lambda: 0.99
  max_grad_norm: 0.3
  vf_coef: 0.9467710647343072
  net_arch: small
  activation_fn: relu
  n_timesteps: 100000
  n_envs: 10

HalfCheetah-v5:
  policy: 'MlpPolicy'
  batch_size: 64
  n_steps: 16
  gamma: 0.9
  learning_rate: 6.562333225476044e-05
  ent_coef: 2.1881234398919925e-08
  clip_range: 0.4
  n_epochs: 10
  gae_lambda: 0.99
  max_grad_norm: 5
  vf_coef: 0.47070192790845444
  net_arch: small
  activation_fn: relu
  n_timesteps: 800000
  n_envs: 10

Hopper-v5:
  policy: 'MlpPolicy'
  batch_size: 512
  n_steps: 256
  gamma: 0.99
  learning_rate: 0.0008786509063566483
  ent_coef: 4.7413036701082044e-08
  clip_range: 0.3
  n_epochs: 5
  gae_lambda: 0.95
  max_grad_norm: 0.6
  vf_coef: 0.8162295327543241
  net_arch: small
  activation_fn: relu
  n_timesteps: 600000
  n_envs: 4

Humanoid-v5:
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 16
  gamma: 0.995
  learning_rate: 1.000900380783336e-05
  ent_coef: 2.034198296337839e-07
  clip_range: 0.4
  n_epochs: 20
  gae_lambda: 0.8
  max_grad_norm: 0.8
  vf_coef: 0.8304599284219261
  net_arch: tiny
  activation_fn: tanh
  n_timesteps: 400000
  n_envs: 10

HumanoidStandup-v5:
  policy: 'MlpPolicy'
  batch_size: 512
  n_steps: 1024
  gamma: 0.9999
  learning_rate: 0.0004948905997087219
  ent_coef: 5.5364049883411455e-05
  clip_range: 0.1
  n_epochs: 10
  gae_lambda: 0.98
  max_grad_norm: 0.3
  vf_coef: 0.602511184087952
  net_arch: small
  activation_fn: tanh
  n_timesteps: 800000
  n_envs: 10

InvertedDoublePendulum-v5:
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 512
  gamma: 0.95
  learning_rate: 0.008853701642334575
  ent_coef: 2.5370668529088744e-08
  clip_range: 0.1
  n_epochs: 10
  gae_lambda: 0.8
  max_grad_norm: 0.3
  vf_coef: 0.6300195360697247
  net_arch: tiny
  activation_fn: tanh
  n_timesteps: 100000
  n_envs: 4

Reacher-v5:
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 128
  gamma: 0.98
  learning_rate: 0.00041003062237224513
  ent_coef: 0.028522726926146675
  clip_range: 0.2
  n_epochs: 5
  gae_lambda: 0.8
  max_grad_norm: 0.8
  vf_coef: 0.7443911275358162
  net_arch: medium
  activation_fn: relu
  n_timesteps: 500000
  n_envs: 6

Swimmer-v5:
  policy: 'MlpPolicy'
  batch_size: 512
  n_steps: 1024
  gamma: 0.995
  learning_rate: 0.0005375507136780008
  ent_coef: 7.896624456190611e-06
  clip_range: 0.4
  n_epochs: 20
  gae_lambda: 0.98
  max_grad_norm: 0.9
  vf_coef: 0.05560006762484643
  net_arch: small
  activation_fn: relu
  n_timesteps: 900000
  n_envs: 6
