Ant-v5:
  policy: 'MlpPolicy'
  batch_size: 512
  n_steps: 2048
  gamma: 0.99
  learning_rate: 0.0013931381527875178
  line_search_shrinking_factor: 0.9
  n_critic_updates: 20
  cg_max_steps: 30
  cg_damping: 0.01
  target_kl: 0.05
  gae_lambda: 0.8
  net_arch: medium
  log_std_init: -2.32457966159704
  sde_sample_freq: 256
  ortho_init: 1
  activation_fn: relu
  lr_schedule: linear
  n_timesteps: 100000
  n_envs: 6

HalfCheetah-v5:
  policy: 'MlpPolicy'
  batch_size: 64
  n_steps: 1024
  gamma: 0.98
  learning_rate: 0.00026434776463304623
  line_search_shrinking_factor: 0.8
  n_critic_updates: 30
  cg_max_steps: 20
  cg_damping: 0.2
  target_kl: 0.01
  gae_lambda: 0.8
  net_arch: small
  log_std_init: -0.6640297978996337
  sde_sample_freq: 8
  ortho_init: 0
  activation_fn: tanh
  lr_schedule: linear
  n_timesteps: 100000
  n_envs: 6

Hopper-v5:
  policy: 'MlpPolicy'
  batch_size: 16
  n_steps: 8
  gamma: 0.9999
  learning_rate: 0.0016985720143707533
  line_search_shrinking_factor: 0.9
  n_critic_updates: 5
  cg_max_steps: 5
  cg_damping: 0.05
  target_kl: 0.01
  gae_lambda: 0.92
  net_arch: medium
  log_std_init: -0.9257540950521486
  sde_sample_freq: 256
  ortho_init: 1
  activation_fn: tanh
  lr_schedule: linear
  n_timesteps: 100000
  n_envs: 10

Humanoid-v5:
  policy: 'MlpPolicy'
  batch_size: 512
  n_steps: 1024
  gamma: 0.98
  learning_rate: 0.0001001422334677667
  line_search_shrinking_factor: 0.7
  n_critic_updates: 25
  cg_max_steps: 25
  cg_damping: 0.5
  target_kl: 0.1
  gae_lambda: 0.99
  net_arch: small
  log_std_init: -1.1830649974937577
  sde_sample_freq: 128
  ortho_init: 0
  activation_fn: relu
  lr_schedule: linear
  n_timesteps: 100000
  n_envs: 2

InvertedDoublePendulum-v5:
  policy: 'MlpPolicy'
  batch_size: 512
  n_steps: 128
  gamma: 0.995
  learning_rate: 0.000641801789987054
  line_search_shrinking_factor: 0.8
  n_critic_updates: 20
  cg_max_steps: 20
  cg_damping: 0.2
  target_kl: 0.005
  gae_lambda: 0.8
  net_arch: medium
  log_std_init: -1.1442557317275153
  sde_sample_freq: 64
  ortho_init: 0
  activation_fn: relu
  lr_schedule: constant
  n_timesteps: 100000
  n_envs: 8

Swimmer-v5:
  policy: 'MlpPolicy'
  batch_size: 64
  n_steps: 128
  gamma: 0.999
  learning_rate: 5.2019645918946135e-05
  line_search_shrinking_factor: 0.7
  n_critic_updates: 25
  cg_max_steps: 5
  cg_damping: 0.2
  target_kl: 0.1
  gae_lambda: 0.98
  net_arch: small
  log_std_init: 0.8744241148020431
  sde_sample_freq: 128
  ortho_init: 1
  activation_fn: relu
  lr_schedule: constant
  n_timesteps: 100000
  n_envs: 10

HumanoidStandup-v5:
  policy: 'MlpPolicy'
  normalize: true
  n_envs: 2
  n_timesteps: 100000
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  line_search_shrinking_factor: 0.7
  target_kl: 0.1
  net_arch: small
  log_std_init: 0.8744241148020431
  sde_sample_freq: 128
  ortho_init: 1
  activation_fn: relu
  lr_schedule: constant
  
Reacher-v5:
  policy: 'MlpPolicy'
  normalize: true
  n_envs: 2
  n_timesteps: 100000
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  line_search_shrinking_factor: 0.7
  target_kl: 0.1
  net_arch: small
  log_std_init: 0.8744241148020431
  sde_sample_freq: 128
  ortho_init: 1
  activation_fn: relu
  lr_schedule: constant

Pusher-v5:
  policy: 'MlpPolicy'
  normalize: true
  n_envs: 2
  n_timesteps: 100000
  batch_size: 128
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.95
  sub_sampling_factor: 1
  cg_max_steps: 25
  cg_damping: 0.1
  n_critic_updates: 20
  learning_rate: !!float 1e-3
  line_search_shrinking_factor: 0.7
  target_kl: 0.1
  net_arch: small
  log_std_init: 0.8744241148020431
  sde_sample_freq: 128
  ortho_init: 1
  activation_fn: relu
  lr_schedule: constant

