component_combinations:
- - reward
  - action
dry_run: false
env_name: HalfCheetah-v5
max_level: 0.5
min_level: -0.5
noise_configs:
  action:
  - uniform
  reward:
  - uniform
num_runs: 5
steps: 6
total_timesteps: 100000
