Humanoid-v5:
  policy: 'MlpPolicy'
  n_steps: 512
  gamma: 0.95
  learning_rate: 0.03648542602737527
  n_critic_updates: 20
  cg_max_steps: 5
  target_kl: 0.03
  gae_lambda: 0.95
  batch_size: 2048
  net_arch: medium
  activation_fn: tanh
  entropy_coef: -0.59
  sampling_coef: -0.69
  buffer_capacity: 30000
  epsilon: 0.15000000000000002
  orthogonal_init: 0
  n_timesteps: 600000
  n_envs: 6
  normalize_advantage: 1
  fd_hidden_dim: 256
  fd_encoder_layers: 1
  fd_forward_layers: 2
  fd_activation: ELU
  fd_lr: 1e-3
  noise_type: uniform
  noise_level: 0.1

HumanoidStandup-v5:
  policy: 'MlpPolicy'
  n_steps: 8
  gamma: 0.8
  learning_rate: 0.11959944479404305
  n_critic_updates: 30
  cg_max_steps: 5
  target_kl: 0.1
  gae_lambda: 1
  batch_size: 2048
  net_arch: large
  activation_fn: tanh
  entropy_coef: 0.24
  sampling_coef: -0.5
  epsilon: 0.75
  orthogonal_init: 1
  n_timesteps: 100000
  n_envs: 4
  normalize_advantage: 0
  fd_hidden_dim: 256
  fd_encoder_layers: 1
  fd_forward_layers: 2
  fd_activation: ELU
  fd_lr: 1e-3
  noise_type: uniform
  noise_level: -0.5