component_combinations:
- - reward
- - action
- - reward
  - action
dry_run: false
env_name: Humanoid-v5
max_level: 0.5
min_level: -0.25
noise_configs:
  action:
  - uniform
  reward:
  - uniform
num_runs: 5
steps: 3
total_timesteps: 100000
